<?php

namespace Omegazord\PresentationBundle\Repository;

/**
 * ExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends \Doctrine\ORM\EntityRepository
{
	public function myFindAll()
	{
	  return $this
	    ->createQueryBuilder('a')
	    ->getQuery()
	    ->getResult()
	  ;
	}
	
	//NE FONCTIONNE PAS !!!
	public function myFindOne($id)
	{
	    $qb = $this->createQueryBuilder('a');
	    
	    $qb->where('a.id = :id')->setParameter('id', $id);
	    
	    return $qb->getQuery()->getResult();
	}
	
	
	public function myFindByLieu($lieu)
	{
	    $qb = $this->createQueryBuilder('a');
	    
	    $qb->where('a.lieu = :lieu')->setParameter('lieu', $lieu);
	    
	    return $qb->getQuery()->getResult();
	}
}
